### ISSUE TITLE
Unable to run the http server

### ISSUE THREAD

**Issue by rpvishnutejak** [unikraft/app-httpreply#7]
I tried all the given steps and also the steps listed in the 2021 Summer internship first lecture but unable to start the unikernal. Build was successful but when running, I always get the following error:
![image](https://user-images.githubusercontent.com/33900595/160768079-5f140139-906b-499a-9ddc-1053941af1ab.png)

I also tried running with qemu-system but that returned bridge not found error. I am struggling with this for weeks now. 

Thanks in advance.

**Comment by skuenzer** [comment]
Oh, this has to do with your TTY settings, `socat` complains. You never saw the serial output of the guest.
